queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@1
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@1
  inputs:
    projects: '**/src/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@1
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: 'false'
    projects: '**/src/**/*.csproj'
    arguments: '--output $(build.artifactstagingdirectory)'
    zipAfterPublish: 'True'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    ArtifactType: 'Container'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'test/'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/tests'
    ArtifactName: 'tests'
    ArtifactType: 'Container'
